config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'volunteers#index'
  resources :posts
  resources :users
  resources :clients do
    scope module: :clients do
      resources :tasks do
        post 'cancel'
      end
    end
  end
  resources :volunteers do
    get 'show_confirm', on: :collection
    post 'confirm', on: :collection
  end
  resources :volunteer_imports, only: [:new, :create]

  resources :tasks, only: [:index, :new, :create, :show] do
    post 'accept'
    post 'finish'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  has_many :tasks, dependent: :nullify, inverse_of: :volunteer
  before_create :generate_token
  scope :with_confirmed, -> { where(is_confirmed: true) }
  scope :not_deleted, -> { where(deleted_at: nil) }
  scope :ordered_by_name, -> { order(name: :asc) }

  validates :email, presence: true, uniqueness: true

  def generate_token
    self.token = SecureRandom.hex
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_admin, only: [:show_confirm, :confirm]

  def index
    @volunteers = Volunteer.not_deleted
  end

  def new
    @volunteer = Volunteer.new
  end

  def create
    @volunteer = Volunteer.new volunteers_params
    if @volunteer.save
      send_email
      redirect_to volunteer_path(@volunteer)
    else
      render :new
    end
  end

  def show
    # set_volunteer()
  end

  def edit
    # set_volunteer()
  end

  def update
    if @volunteer.update volunteers_params
      redirect_to volunteer_path(@volunteer)
    else
      render :edit
    end
  end

  def destroy
    if @volunteer.deleted_at == nil
      @volunteer.update! is_confirmed: false, deleted_at: Time.now
    end
    redirect_to volunteers_path
  end

  def show_confirm
    @volunteer = Volunteer.find_by!(token: params[:token])
  end

  def confirm
    @volunteer = Volunteer.find_by!(token: params[:token])
    if !@volunteer.is_confirmed
      @volunteer.update! name: params[:name], is_confirmed: true
    end
    redirect_to tasks_path
  end

private

  def send_email
    magic_link = show_confirm_volunteers_url(token: @volunteer.token)
    VolunteerMailer.new_magic_link(@volunteer.email, magic_link).deliver_now
  end

  def set_volunteer
    @volunteer = Volunteer.find(params[:id])
  end

  def volunteers_params
    params.require(:volunteer).permit(:name, :email)
  end
end

app/views/volunteers/_form.html.erb
<div class="row">
    <div class="col-12">
        <%= form_with model: volunteer do |form| %>
        <div class="row mb-3">
            <%= form.label :name %>
            <div class="col-sm-6">
                <%= form.text_field :name %>
            </div>
        </div>
        <div class="row mb-3">
            <%= form.label :email %>
            <div class="col-sm-6">
                <%= form.email_field :email, required: true %>
            </div>
        </div>
        <%= form.button send_label, class: "btn btn-primary" %>
        <% end %>
        <br>
        <%= link_to "Zrušit", volunteers_path, class: "btn btn-secondary" %>
    </div>
</div>

app/views/volunteers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Upravit dobrovolníka</h1>
            <%= render "form", volunteer: @volunteer, send_label: "Aktualizovat" %>
        </div>
    </div>
</div>

app/views/volunteers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <h2 class="col-6">Dobrovolníci</h2>
        <% if is_admin? %>
          <div class="col-6 text-end">
            <%= link_to "Nový dobrovolník", new_volunteer_path, class: "btn btn-primary" %>
            <%= link_to "Importovat dobrovolníky", new_volunteer_import_path, class: "btn btn-primary" %>
          </div>
        <% end %>
        <br>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th>
                Jméno
              </th>
              <th>
                Email
              </th>
              <th>
                Potvrzen
              </th>
            </tr>
          </thead>
          <tbody>
            <% @volunteers.each do |volunteer| %>
            <tr>
              <td>
                <%= link_to volunteer.name, volunteer_path(volunteer)  %>
              </td>
              <td>
                <%= volunteer.email %>
              </td>
              <td>
                <% if volunteer.is_confirmed %>
                    <i class="fas fa-check"></i>
                <% else %>
                    <i class="fas fa-times"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/volunteers/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Vytvořit nového dobrovolníka</h1>
            <%= render "form", volunteer: @volunteer, send_label: "Vytvořit" %>
        </div>
    </div>
</div>

app/views/volunteers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="card" style="width: 18rem;">
                <% if @volunteer.deleted_at == nil %>
                    <div class="card-body">
                <% else %>
                    <div class="card-body text-secondary">
                <% end %>
                    <h1 class="card-title"> <%= @volunteer.name %> </h1>
                    <p class="card-text">
                        <%= @volunteer.email %>
                    </p>
                    <br>
                    <div class="row">
                        <% if @volunteer.deleted_at == nil %>
                            <div class="col">
                                <%= link_to "Upravit", edit_volunteer_path(@volunteer), class: "btn btn-primary" %>
                            </div>
                            <div class="col text-end">
                                <% if is_admin? && @volunteer.deleted_at == nil %>
                                    <%= link_to "Smazat", volunteer_path(@volunteer), method: :delete, data: { confirm: "Opravdu chcete označit dobrovolníka #{@volunteer.name} jako smazaného?" }, class: "btn btn-danger" %>
                                <% end %>
                            </div>
                        <% else %>
                            <div class="col">
                                <p>(Dobrovolník byl smazaný)</p>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
            <br>
            <%= link_to "Zpět", volunteers_path, class: "btn btn-secondary" %>
        </div>
    </div>
</div>

app/views/volunteers/show_confirm.html.erb
<div class="container">
    <div class="row">
        <div class="col-12 text-center">
            <%= form_with url: confirm_volunteers_path do |form| %>
                <%= form.hidden_field :token, value: @volunteer.token %>
                <% if @volunteer.is_confirmed %>
                    <%= form.button "Přihlásit se", class: "btn btn-primary" %>
                <% else %>
                    <%= form.label "Jméno" %>
                    <%= form.text_field :name, value: @volunteer.name, required: true%>
                    <br>
                    <br>
                    <%= form.button "Potvrdit", class: "btn btn-primary" %>
                <% end %>
            <% end %>
        </div>
    </div>
</div>