config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'volunteers#index'
  resources :posts
  resources :users
  resources :clients do
    scope module: :clients do
      resources :tasks do
        post 'cancel'
      end
    end
  end
  resources :volunteers do
    get 'show_confirm', on: :collection
    post 'confirm', on: :collection
  end
  resources :volunteer_imports, only: [:new, :create]

  resources :tasks, only: [:index, :new, :create, :show] do
    post 'accept'
    post 'finish'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy, inverse_of: :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new users_params
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end
  def show
    #set_user()
  end
  def edit
    #set_user()
  end
  def update
    if @user.update users_params
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  def destroy
    @user.destroy
    redirect_to users_path
  end


  private
  def set_user
    @user = User.find(params[:id])
  end
  def users_params
    params.require(:user).permit(:name, :email, :phone_number)
  end
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
<%= form.label :name %>:
<%= form.text_field :name %>
<br>
<br>
<%= form.label :email %>:
<%= form.email_field :email %>
<br>
<br>
<%= form.label :phone_number %>:
<%= form.text_field :phone_number %>
<br>
<br>
<%= form.button %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Index</h1>
<p>Currently there is <%= @users.size %> users</p>
<%= link_to "New user", new_user_path %>
<%= link_to "Posts", posts_path %>
<br>
<table>
  <thead>
    <tr>
      <th>
        ID
      </th>
      <th>
        Name
      </th>
      <th>
        Email
      </th>
      <th>
        Phone
      </th>
      <th>

      </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.id %>
      </td>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= user.email %>
      </td>
      <td>
        <%= user.phone_number %>
      </td>
      <td>
        <%= link_to "Show", user_path(user) %>
        <%= link_to "Edit", edit_user_path(user) %>
        <%= link_to "Delete", user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>
<p> <%= @user.email %> </p>
<p> <%= @user.phone_number %> </p>
<br>
<%= link_to "Return", users_path %>