config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'volunteers#index'
  resources :posts
  resources :users
  resources :clients do
    scope module: :clients do
      resources :tasks do
        post 'cancel'
      end
    end
  end
  resources :volunteers do
    get 'show_confirm', on: :collection
    post 'confirm', on: :collection
  end
  resources :volunteer_imports, only: [:new, :create]

  resources :tasks, only: [:index, :new, :create, :show] do
    post 'accept'
    post 'finish'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, inverse_of: :posts
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.includes :user
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.new posts_params
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end
  def show
    #set_post()
  end
  def edit
    #set_post()
  end
  def update
    if @post.update posts_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end
  def destroy
    @post.destroy
    redirect_to posts_path
  end


  private
  def set_post
    @post = Post.find(params[:id])
  end
  def posts_params
    params.require(:post).permit(:name, :text, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if post.errors.any? %>
<h2>These errors must be resolved</h2>
<ul>
  <% post.errors.full_messages.each do |error| %>
    <li>
      <%= error %>
    </li>
  <% end %>
</ul>
<% end %>
<%= form_with model: post do |form| %>
<%= form.label :name %>:
<%= form.text_field :name %>
<br>
<br>
<%= form.label :text %>:
<%= form.text_area :text %>
<br>
<br>
<%= form.label :user_id %>:
<%= form.select :user_id, options_for_select(User.all.map { |user| [user.name, user.id] }, post.user_id), include_blank: true %>
<br>
<br>
<%= form.button %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Index</h1>
<p>Currently there is <%= @posts.size %> posts</p>
<%= link_to "New post", new_post_path %>
<%= link_to "Users", users_path %>
<br>
<table>
  <thead>
    <tr>
      <th>
        ID
      </th>
      <th>
        Name
      </th>
      <th>
        User
      </th>
      <th>

      </th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td>
        <%= post.id %>
      </td>
      <td>
        <%= post.name %>
      </td>
      <td>
        <%= post.user.name %>
      </td>
      <td>
        <%= link_to "Show", post_path(post) %>
        <%= link_to "Edit", edit_post_path(post) %>
        <%= link_to "Delete", post_path(post), method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Create new post</h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1> <%= @post.name %> </h1>
<p> <%= @post.text %> </p>
<br>
<%= link_to "Return", posts_path %>