config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'volunteers#index'
  resources :posts
  resources :users
  resources :clients do
    scope module: :clients do
      resources :tasks do
        post 'cancel'
      end
    end
  end
  resources :volunteers do
    get 'show_confirm', on: :collection
    post 'confirm', on: :collection
  end
  resources :volunteer_imports, only: [:new, :create]

  resources :tasks, only: [:index, :new, :create, :show] do
    post 'accept'
    post 'finish'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_logo.html.erb
<a class="page-logo with-claim"><span title="Život 90" class="icon icon-logo_zivot90" role="img"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 200 71.9" style="enable-background:new 0 0 200 71.9;" xml:space="preserve">
	<g class="logo-claim">
	<path d="M9.3,63.2H7.9c-0.3-1.4-1.2-2.3-3.2-2.3c-1.7,0-2.8,0.8-2.8,2.1c0,1,0.7,1.6,2.1,1.9L6,65.3
		c2.1,0.4,3.3,1.4,3.3,3.1c0,2.1-1.8,3.5-4.4,3.5c-2.8,0-4.6-1.4-4.9-4h1.3c0.3,1.8,1.5,2.7,3.6,2.7c1.8,0,2.9-0.8,2.9-2.1
		c0-0.9-0.6-1.7-2.1-1.9l-2.2-0.4c-2.1-0.4-3.1-1.5-3.1-3.1c0-2.1,1.7-3.4,4.2-3.4C7,59.8,9,60.8,9.3,63.2"></path>
	<polygon points="25.8,59.9 25.8,69.3 18.3,59.9 17.2,59.9 17.2,71.6 18.5,71.6 18.5,62.4 26,71.6 27.1,71.6 27.1,59.9"></polygon>
	<path d="M35,61.5l2.5,5.6h-5L35,61.5z M34.3,59.9L29,71.6h1.5l1.4-3.3h6l1.4,3.3h1.5l-5.3-11.7H34.3z M35.7,56.1
		l-1.4,2.5h1.2l1.6-2.5H35.7z"></path>
	<polygon points="53.2,59.9 48.6,67.8 43.9,59.9 42.8,59.9 42.8,71.6 44.2,71.6 44.2,62.9 48.1,69.4 49,69.4 52.9,62.9
		52.9,71.6 54.3,71.6 54.3,59.9 	"></polygon>
	<rect x="57.5" y="59.9" width="1.4" height="11.7"></rect>
	<path d="M75.7,63.5h-2.3c-0.2-1.1-0.8-1.8-2.3-1.8c-1.3,0-2.1,0.5-2.1,1.5c0,0.8,0.6,1.2,1.7,1.4l1.4,0.3
		c2.3,0.5,3.6,1.3,3.6,3.3c0,2.2-1.8,3.7-4.6,3.7c-2.9,0-4.9-1.6-5.1-4.1h2.3c0.2,1.2,1.3,2,2.9,2c1.3,0,2-0.5,2-1.3
		c0-0.5-0.3-1.1-1.6-1.3l-1.9-0.4c-2.3-0.4-3.3-1.6-3.3-3.4c0-2.2,1.8-3.7,4.4-3.7C72.8,59.7,75.4,60.5,75.7,63.5"></path>
	<path d="M82.6,62.7l1.8,4.5h-3.7L82.6,62.7z M81.5,59.9l-5.1,11.7h2.5l1-2.3h5.4l1,2.3h2.5l-5.1-11.7H81.5z"></path>
	<polygon points="100.8,59.9 96.3,67 91.9,59.9 90.2,59.9 90.2,71.6 92.6,71.6 92.5,65 95.6,69.9 95.6,69.9 97,69.9
		100.1,65.1 100.1,71.6 102.4,71.6 102.4,59.9 	"></polygon>
	<rect x="105.1" y="59.9" width="2.3" height="11.7"></rect>
	<path d="M124.1,63.7h-3.5c-0.2-0.7-0.6-1.2-1.6-1.2c-0.8,0-1.3,0.3-1.3,0.9c0,0.5,0.3,0.7,1.1,0.9l1.9,0.4
		c2,0.4,3.4,1.3,3.4,3.4c0,2.4-2,3.9-5.1,3.9c-2.4,0-5.1-1-5.5-4.2h3.5c0.2,0.9,0.9,1.4,2,1.4c0.8,0,1.3-0.3,1.3-0.8
		c0-0.3-0.1-0.7-0.9-0.8l-2-0.5c-2.3-0.5-3.4-1.5-3.4-3.4c0-2.5,2-3.9,4.8-3.9C120.8,59.7,123.8,60.3,124.1,63.7"></path>
	<polygon points="125.8,59.9 125.8,71.6 134.9,71.6 134.9,68.7 129.3,68.7 129.3,67.2 134.1,67.2 134.1,64.4
		129.3,64.4 129.3,62.8 134.9,62.8 134.9,59.9 	"></polygon>
	<path d="M143.7,67.9c0-0.6-0.4-0.9-1.4-0.9h-2.2v2h2.1C143.2,68.9,143.7,68.5,143.7,67.9 M140.1,62.6v2h1.7
		c0.9,0,1.4-0.4,1.4-1.1c0-0.7-0.5-0.9-1.4-0.9H140.1z M147.1,68.4c0,2-1.5,3.3-4.2,3.3h-6.3V59.9h5.8c2.6,0,4.1,1.2,4.1,3.1
		c0,1-0.6,2.2-1.6,2.6C146.3,66,147.1,67.2,147.1,68.4"></path>
	<path d="M157.1,65.8c0-1.5-1.2-2.9-2.8-2.9c-1.6,0-2.8,1.3-2.8,2.9c0,1.5,1.2,2.9,2.8,2.9
		C155.9,68.6,157.1,67.3,157.1,65.8 M160.6,65.8c0,3.5-2.6,6.1-6.3,6.1c-3.7,0-6.3-2.6-6.3-6.1c0-3.5,2.6-6.1,6.3-6.1
		C158,59.7,160.6,62.3,160.6,65.8"></path>
	<path d="M173.2,66c0,3.8-2.1,5.9-5.7,5.9s-5.7-2.1-5.7-5.9v-6h3.5v6.2c0,1.6,0.8,2.5,2.1,2.5c1.3,0,2.1-0.9,2.1-2.5
		v-6.2h3.5V66z"></path>
	</g>
	<polygon points="1.2,9 1.2,13.1 24.5,13.1 0.5,45.6 0.5,48 31.2,48 31.2,43.9 7.5,43.9 31,11.3 31,9 	"></polygon>
	<rect x="37.8" y="9" width="7.8" height="39"></rect>
	<polygon points="93.8,9 76.9,48.2 67.1,48.2 50.2,9 60.9,9 72,35.4 83.1,9 	"></polygon>
	<path d="M124.2,28.5c0-5.1-3.8-9.5-9.3-9.5c-5.5,0-9.3,4.4-9.3,9.5c0,5.1,3.8,9.5,9.3,9.5
		C120.4,38,124.2,33.6,124.2,28.5 M136,28.5c0,11.5-8.7,20.3-21.1,20.3c-12.3,0-21.1-8.8-21.1-20.3c0-11.5,8.7-20.3,21.1-20.3
		C127.3,8.2,136,16.9,136,28.5"></path>
	<polygon points="173.2,20.4 162.4,20.4 162.4,48 148.9,48 148.9,20.4 138.1,20.4 138.1,9 173.2,9 	"></polygon>
	<path d="M184.5,14c0.1-0.2,0.2-0.5,0.2-0.7c0-0.6-0.6-1.3-1.4-1.3c-0.8,0-1.4,0.7-1.4,1.3c0,0.6,0.6,1.3,1.4,1.3
		c0.4,0,0.8-0.1,1-0.3L184.5,14z M188.2,13.4c0,0.8-0.4,1.8-0.8,2.5l-2.9,4.6h-4.3l2-3.1c-2.4-0.4-3.9-2-3.9-4c0-2.5,2-4.5,5-4.5
		C186.3,8.9,188.2,10.8,188.2,13.4"></path>
	<path d="M196.5,14.8c0-1.6-0.8-2.7-2.1-2.7c-1.3,0-2.1,1.1-2.1,2.7c0,1.6,0.8,2.7,2.1,2.7
		C195.7,17.5,196.5,16.4,196.5,14.8 M200,14.8c0,3.5-2.2,5.9-5.5,5.9c-3.3,0-5.6-2.4-5.6-5.9c0-3.5,2.2-5.9,5.6-5.9
		C197.8,8.9,200,11.3,200,14.8"></path>
	<polygon points="19.1,0 16,3.5 12.8,0 8.5,0 13.7,6.2 18.2,6.2 23.4,0 	"></polygon>
</svg>
<noscript>Život 90</noscript></span></a>

app/views/layouts/_navbar.html.erb
<% if is_admin? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark navbar-volunteer">
  <%= render "layouts/logo" %>
<% end %>
    <div class="container">
        <% if is_admin? %>
          <a class="navbar-brand">Život 90</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if is_admin? %>
              <li class="nav-item">
                <%= link_to "Klienti", clients_path, class: "nav-link #{'active' if current_page?(clients_path)}", 'aria-current': "page" %>
              </li>
              <li class="nav-item">
                <%= link_to "Dobrovolníci", volunteers_path, class: "nav-link #{'active' if current_page?(volunteers_path)}", 'aria-current': "page" %>
              </li>
              <li class="nav-item">
                <%= link_to "Nová poptávka", new_task_url, class: "nav-link #{'active' if current_page?(new_task_url)}", 'aria-current': "page" %>
              </li>
            <% elsif current_user.is_confirmed %>
              <li class="nav-item">
                <%= link_to "Poptávky", tasks_path, class: "nav-link #{'active' if current_page?(tasks_path)}", 'aria-current': "page" %>
              </li>
            <% end %>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <br>
    <%= yield %>
  </body>
</html>